APPROVED_ENTITY_LABELS = {
    'PERSON', 'NORP', 'FAC', 'ORG', 'GPE', 'LOC', 'PRODUCT', 'EVENT', 'WORK_OF_ART',
    'LAW', 'LANGUAGE', 'DATE', 'TIME', 'PERCENT', 'MONEY', 'QUANTITY', 'ORDINAL', 'CARDINAL'
}

APPROVED_RELATIONSHIPS = {
    'IS_A', 'PART_OF', 'LOCATED_IN', 'WORKS_FOR', 'FOUNDED', 'CEO_OF', 'CREATED', 'OWNS',
    'MEMBER_OF', 'BORN_IN', 'DIED_IN', 'SPOUSE_OF', 'PARENT_OF', 'CHILD_OF', 'SIBLING_OF',
    'PREDECESSOR_OF', 'SUCCESSOR_OF', 'CONTAINS', 'SUBCLASS_OF', 'INSTANCE_OF', 'HAS_PROPERTY',
    'AUTHORED_BY', 'DIRECTED_BY', 'PRODUCED_BY', 'PERFORMED_BY', 'AFFILIATED_WITH',
    'COLLABORATES_WITH', 'COMPETES_WITH', 'SUPPLIES', 'USES', 'CAUSES', 'PREVENTS',
    'SYMPTOMS_OF', 'TREATS', 'STUDIES', 'RESEARCHES', 'DISCOVERS', 'INVENTS', 'DEVELOPS',
    'IMPLEMENTS', 'MANUFACTURES', 'SELLS', 'BUYS', 'EXPORTS', 'IMPORTS', 'REGULATES',
    'GOVERNS', 'REPRESENTS', 'VOTES_FOR', 'SUPPORTS', 'OPPOSES', 'ANNOUNCES', 'LEADS',
    'HEADQUARTERED_IN'
}
